### ISSUE TITLE
Ruby 3.2 compat of `Mustermann::Rails#expand`

### ISSUE THREAD

**Issue by jodosha** [sinatra/mustermann#135]
Hi folks,
I was testing `hanami-router` with Ruby 3.2 preview3 and ran into this error.

Steps to reproduce:

```ruby
require "mustermann/rails"

route = Mustermann::Rails.new("/books/:id")
variables = {id: 23}

route.expand(:append, variables)
# => *** NoMethodError Exception: undefined method `=~' for 23:Integer
```

Here's the stack trace taken from a failed spec:

```
Failures:

  1) Hanami::Router#path recognizes string with variables and constraints
     Failure/Error:
       @named.fetch(name.to_sym) do
         raise MissingRouteError.new(name)
       end.expand(:append, variables)

     NoMethodError:
       undefined method `=~' for 23:Integer
     # /Users/jodosha/.gem/ruby/3.2.0/gems/mustermann-1.1.2/lib/mustermann/ast/expander.rb:128:in `escape'
     # /Users/jodosha/.gem/ruby/3.2.0/gems/mustermann-1.1.2/lib/mustermann/ast/expander.rb:99:in `block in expand'
     # /Users/jodosha/.gem/ruby/3.2.0/gems/mustermann-1.1.2/lib/mustermann/ast/expander.rb:99:in `each'
     # /Users/jodosha/.gem/ruby/3.2.0/gems/mustermann-1.1.2/lib/mustermann/ast/expander.rb:99:in `expand'
     # /Users/jodosha/.gem/ruby/3.2.0/gems/mustermann-1.1.2/lib/mustermann/expander.rb:150:in `expand'
     # /Users/jodosha/.gem/ruby/3.2.0/gems/mustermann-1.1.2/lib/mustermann/expander.rb:182:in `with_rest'
     # /Users/jodosha/.gem/ruby/3.2.0/gems/mustermann-1.1.2/lib/mustermann/expander.rb:152:in `expand'
     # /Users/jodosha/.gem/ruby/3.2.0/gems/mustermann-1.1.2/lib/mustermann/ast/pattern.rb:108:in `expand'
     # ./lib/hanami/router/url_helpers.rb:29:in `path'
     # ./lib/hanami/router.rb:459:in `path'
     # ./spec/unit/hanami/router/path_spec.rb:31:in `block (3 levels) in <top (required)>'
```
